//
// Created by Youssef on 18/10/2025.
//

#ifndef ADVANCEDPROGRAMMING_PACMAN_STATEMANAGER_H
#define ADVANCEDPROGRAMMING_PACMAN_STATEMANAGER_H


class StateManager {
};


#endif //ADVANCEDPROGRAMMING_PACMAN_STATEMANAGER_H